version: "3"

services:
    mysqldb:
        image: mysql:5.7
        environment:
            - MYSQL_DATABASE=job_finder
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_ROOT_HOST=%
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        ports:
            - "3306:3306"
        restart: always
        volumes:
            - ./db:/var/lib/mysql
    job-finder:
        build: .
        environment:
            - MYSQL_HOST=mysqldb
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_PORT=3306
        ports:
            - "8080:8080"
        depends_on:
            - mysqldb
        restart: always
